//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.SongList = new HashSet<SongList>();
        }
    
        public int A_Id { get; set; }
        public int A_SingerId { get; set; }
        public string A_Name { get; set; }
        public string A_Info { get; set; }
        public string A_Song { get; set; }
        public System.DateTime A_Time { get; set; }
        public string A_Img { get; set; }
        public Nullable<int> A_PlayCount { get; set; }
        public int IsDelete { get; set; }
    
        public virtual Singer Singer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongList> SongList { get; set; }
    }
}
