//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dynamic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dynamic()
        {
            this.DynamicComment = new HashSet<DynamicComment>();
        }
    
        public int D_Id { get; set; }
        public int D_UserId { get; set; }
        public string D_Title { get; set; }
        public System.DateTime D_UpTime { get; set; }
        public string D_Content { get; set; }
        public Nullable<int> D_GoodCount { get; set; }
        public Nullable<int> D_SongID { get; set; }
        public string D_imgs { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicComment> DynamicComment { get; set; }
    }
}
