//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YoungMusicEntities : DbContext
    {
        public YoungMusicEntities()
            : base("name=YoungMusicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<Dynamic> Dynamic { get; set; }
        public virtual DbSet<DynamicComment> DynamicComment { get; set; }
        public virtual DbSet<MenuComment> MenuComment { get; set; }
        public virtual DbSet<Singer> Singer { get; set; }
        public virtual DbSet<SongComment> SongComment { get; set; }
        public virtual DbSet<SongList> SongList { get; set; }
        public virtual DbSet<SongMenu> SongMenu { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
