//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SongMenu()
        {
            this.MenuComment = new HashSet<MenuComment>();
        }
    
        public int M_Id { get; set; }
        public int M_UserId { get; set; }
        public string M_Name { get; set; }
        public string M_Info { get; set; }
        public string M_SongId { get; set; }
        public System.DateTime M_CreatTime { get; set; }
        public string M_Img { get; set; }
        public int M_Type { get; set; }
        public Nullable<int> M_PlayCount { get; set; }
        public Nullable<int> M_CollectCount { get; set; }
        public Nullable<int> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuComment> MenuComment { get; set; }
        public virtual Type Type { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
