//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SongList()
        {
            this.SongComment = new HashSet<SongComment>();
        }
    
        public int S_Id { get; set; }
        public string S_Name { get; set; }
        public int S_Type { get; set; }
        public int S_Singer { get; set; }
        public string S_Url { get; set; }
        public string S_Cover { get; set; }
        public Nullable<int> S_PlayCount { get; set; }
        public Nullable<int> S_CollectCount { get; set; }
        public System.DateTime S_UpTime { get; set; }
        public string S_Lyric { get; set; }
        public Nullable<int> S_Album { get; set; }
        public Nullable<int> S_Audit_State { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string WYID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Singer Singer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongComment> SongComment { get; set; }
        public virtual Type Type { get; set; }
    }
}
